name: update data


on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: scraping data
      env:
        TZ: Asia/Tokyo
      run:
        python src/scraping.py
    - name: Run auto update script
      env:
        NAME: Retsuki
        EMAIL: retu1118@gmail.com
      run: |
        TODAY=`date "+%Y/%m/%d %H:%M"`
        git config --local user.email NAME
        git config --local user.name EMAIL
        git status | grep modified && git add src/ && git commit -v -m "データ更新 ${TODAY}" \
          && curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/Retsuki/covid19-ishikawa/dispatches --data '{"event_type": "build_application"}' \
          || true
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

